// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/HT4w5/l4rt/pkg/modules/context"
	"github.com/HT4w5/l4rt/pkg/modules/handler"
	"github.com/HT4w5/l4rt/pkg/modules/log"
)

// Injectors from wire.go:

func InitializeCore(cfg Config) (App, func(), error) {
	managerConfig := ProvideContextManagerConfig(cfg)
	manager := context.NewManager(managerConfig)
	factoryConfig := ProvideLogFactoryConfig(cfg)
	factory, cleanup := log.NewFactory(factoryConfig)
	handlersFactoryConfig := ProvideHandlerFactoryConfig(cfg)
	handlersFactory := handler.NewFactory(handlersFactoryConfig, factory, manager)
	core, err := NewCore(cfg, manager, factory, handlersFactory)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return core, func() {
		cleanup()
	}, nil
}
